### ISSUE TITLE
Can't receive a call.

### ISSUE THREAD

**Issue by hellosmith420** [sightcall/iOS-SDK-Helper#2]
At first, I shall give you many thanks for this sample.
I have successfully build the sample and it is working fine. I can use this app as caller, but not callee.
I am using the https://github.com/sightcall/one-to-one-js-sample in one side and this app in other side.

Using one to one sample I can send and receive a call in browser.
From this app I can call to one to one js based callee and everything works fine.
But, when I use the web based js app as caller and ios based this app as callee, call not happen. web based JS app shows 
Callee 
Terminated
Duration 00.00
Unreachable

**Comment by RomainGabriel** [comment]
Hi there,
I would suggest you to log into your https://saportal.sightcall.com account and contact the support from the "Help" tab. We will be able to have a look at your account and understand better your issue. 
Regards.
