### ISSUE TITLE
connect disconnect connect throwing me error

### ISSUE THREAD

**Issue by ektas** [sightcall/iOS-SDK-Helper#3]
I installed the demo, I connected successfully, I disconnected successfully. When I again tap on connect I see error -259 which say singleton already exists. please tell me know can I connect disconnect within app. Rightnow I need to kill the app from background to connect again.

**Comment by RomainGabriel** [comment]
Hi, we just updated the Helper so it won't happen anymore. Note the Helper still uses an old SDK version and we highly suggest to browse our iOS tutorials: https://docs.sightcall.com/GD/02_iOS_SDK/09_Tutorials/
Regards.
