### ISSUE TITLE
Aftre disconnect, cant connect again. get error "sington already created"

### ISSUE THREAD

**Issue by hellosmith420** [sightcall/iOS-SDK-Helper#4]
Thanks for this nice source code. It is working properly, except one issue I got, so far.
1. Connected successfully and did a demo call session.
2. Tap disconnect and successfully disconnected.
3. Again tap to connect. Get following error.

-[RtccDelegate rtccConnect:]_block_invoke Error: Singleton already created (Error code: 0x103)

Thanks,
John.

**Comment by RomainGabriel** [comment]
Hi John,
This is a known issue, but the SDK-Helper is not updated anymore. We highly recommend to use our tutorials instead: https://docs.sightcall.com/GD/02_iOS_SDK/09_Tutorials/

Regards.
