### ISSUE TITLE
Accept no video (act_novideo)

### ISSUE THREAD

**Issue by hellosmith420** [sightcall/iOS-SDK-Helper#5]
Application showing video even if user select the no video option. 
Is the "resumeWithoutVideo" is not working good?

**Comment by RomainGabriel** [comment]
Hi there,
This iOS-SDK-Helper application is outdated and still uses an old 5.3 SDK. We do not support it anymore and we highly recommend to use our tutorials instead: https://docs.sightcall.com/GD/02_iOS_SDK/09_Tutorials/
Regards.
